MTC - CAN return processor errors + documentation
Hyp-ed/hyped-2023 pull request #108
Opened 2023-03-23 23:08 UTC by TomLonergan03

Changed CanProcessor and ICanProcessor to return `core::Result::kFailure` if a processor fails to process its message

Also added doc comments to CAN classes

2023-03-27 14:38 UTC, maxguy2001 requested changes

2023-03-27 14:38 UTC, maxguy2001 commented on lib/io/hardware_can.cpp
> +  core::Result process_successful = core::Result::kSuccess;
Why do you make this object instead of just returning `kFailure` when the condition is met and `kSuccess` otherwise?

2023-03-27 14:38 UTC, maxguy2001 commented on lib/io/can.hpp
>    virtual void addProcessor(const std::uint16_t id, std::shared_ptr<ICanProcessor> processor) = 0;
Can this not fail too? Not 100% sure on context here but if this could fail then a `core::Result` return value might make sense here too?

2023-03-27 14:38 UTC, maxguy2001 commented on lib/io/can.hpp
> +   * @brief Called by ICan::receive() when a message with the given ID is received
Do you not want to include what the function actually does a little bit here?

2023-03-27 14:38 UTC, maxguy2001 commented on lib/io/can.hpp
> +   * registered processors, core::Result::kFailure if a message is not received successfully or if a
Do we log which of the fail states occur?

2023-05-15 17:05 UTC, kshxtij approved these changes

2023-05-15 17:06 UTC, davidbeechey approved these changes

2023-05-15 17:07 UTC, merged