SNS - Add GPIO to REPL
Hyp-ed/hyped-2023 pull request #118
Opened 2023-05-28 22:27 UTC by TomLonergan03

2023-05-31 15:34 UTC, SnickeyX approved these changes
hope this got tested

2023-06-01 00:42 UTC, TomLonergan03 commented
> hope this got tested

hope u tested the mux code lmao

will test tomorrow/fri

2023-06-03 01:49 UTC, SnickeyX requested changes

2023-06-03 01:49 UTC, SnickeyX commented on lib/debug/repl.hpp
replace hardware_gpio with hardware_gpio_alt for testing

2023-06-12 03:41 UTC, kshxtij approved these changes

2023-06-12 03:41 UTC, merged