SNS - GPIO
Hyp-ed/hyped-2023 pull request #12
Opened 2022-10-24 17:22 UTC by Knhwong

2022-10-24 17:53 UTC, kshxtij reviewed
Why were the files within scripts/hooks removed?

2022-10-24 22:00 UTC, mifrandir requested changes
Id get rid of most of this old interface. What was so bad about the dummy that was there before?

2022-10-24 22:00 UTC, mifrandir commented on lib/io/gpio.cpp
> +void Gpio::exportGPIO()
exportGpio

2022-10-24 22:00 UTC, mifrandir commented on lib/io/gpio.cpp
> +uint8_t Gpio::Write(const uint8_t pin, const bool SetOrClear) {
Gpio::write

2022-11-07 18:14 UTC, Knhwong commented
#34

2022-11-07 18:14 UTC, closed without merging