SNS - ADC Logging
Hyp-ed/hyped-2023 pull request #15
Opened 2022-10-25 19:03 UTC by kshxtij

Add logging interface to `io::ADC` and replace all comments with actual logging

2022-10-27 15:30 UTC, SnickeyX requested changes

2022-10-27 15:30 UTC, SnickeyX commented on lib/io/adc.cpp
> +    logger_.log(hyped::core::LogLevel::kInfo, "Failed to reset file offset");
How are we differentiating between info and fatal errors? This seems just as bad as not being able to open the ADC file.

2022-10-27 15:30 UTC, SnickeyX commented on lib/io/adc.cpp
> +    logger_.log(hyped::core::LogLevel::kInfo, "Failed to read 4 bytes");
Same thing here

2022-10-27 17:03 UTC, TomLonergan03 reviewed
I agree with Ishan on levels, once that's done I'm happy with it

2022-10-28 13:53 UTC, SnickeyX approved these changes
looks good

2022-10-31 15:14 UTC, SnickeyX commented on lib/io/adc.cpp
> +Adc::Adc(const uint32_t pin, hyped::core::ILogger &logger) : pin_(pin), logger_(logger)
uint8_t pls

2022-10-31 15:14 UTC, SnickeyX commented on lib/io/adc.hpp
> +  Adc(const uint32_t pin, hyped::core::ILogger &logger);
same here

2022-10-31 16:27 UTC, SnickeyX approved these changes

2022-10-31 17:21 UTC, TomLonergan03 approved these changes

2022-10-31 17:22 UTC, merged