Abstract GPIO and dummy
Hyp-ed/hyped-2023 pull request #17
Opened 2022-10-27 09:39 UTC by mifrandir

Improves GPIO in the following ways:
1. Groups interfaces into lib/io/gpio.hpp to reduce file clutter.
2. Groups real implementation in lib/io/real_gpio.[ch]pp to avoid accidentally importing the non-abstract version. (Open for better naming suggestions.)
3. Adds a set of dummy GPIO classes that (a) show that/how the interface works, and (b) allows for some trivial tests.
4. Abstracts away the hardware to allow for software only tests; for example one could implement a connected GPIO pair (or even a network but that seems overkill) to allow for simulations where we can set GPIO pins at will and see how the pod reacts. 

This approach, if approved, could be taken for I2C, ADC, SPI, and CAN. The latter sounds paritcularly interesting if we are to implement a simulated CAN bus.

2022-10-27 14:06 UTC, kshxtij commented
hardware_gpio.cpp for naming maybe?

2022-10-27 14:22 UTC, kshxtij commented
For CAN we can use `vcan` and the virtual can interface exposed by socketcan instead of having to write a can simulator ourself.

We aren't using SPI for anything this year, so don't need that just yet.

Agreed for I2C and ADC, however with I2C we need to prioritize the multiplexer testing right now so that's on the backburner. 

I'll implement an interface for PWM while the driver code is being written.

2022-10-28 13:49 UTC, SnickeyX requested changes
Minor changes only. This makes the purpose of the reader and writer much clearer.

2022-10-28 13:49 UTC, SnickeyX commented on test/utils/dummy_gpio.cpp
> +  testRead(dummy_gpio, 4, "read 4\n");
can we have 'read from 4' instead

2022-10-28 19:30 UTC, SnickeyX requested changes

2022-10-28 19:30 UTC, SnickeyX commented on test/utils/dummy_gpio.cpp
> +TEST(DummyGpio, printToStderr)
since this is printToStderr, why arent we writing to cerr instead?

2022-10-31 14:12 UTC, kshxtij approved these changes
LGTM but i agree with renaming the test

2022-10-31 15:46 UTC, mifrandir commented on lib/io/hardware_gpio.hpp
> +  virtual std::optional<std::shared_ptr<IGpioWriter>> getWriter(const std::uint8_t pin);
Preference I suppose? Not sure we've agreed on one or the other.

2022-10-31 16:26 UTC, SnickeyX commented on lib/io/hardware_gpio.hpp
> +  virtual std::optional<std::shared_ptr<IGpioWriter>> getWriter(const std::uint8_t pin);
Fair, just wanted to know if it was better practice to do this instead

2022-10-31 16:26 UTC, SnickeyX approved these changes

2022-10-31 16:55 UTC, merged