Logging macros
Hyp-ed/hyped-2023 pull request #56
Opened 2022-11-21 14:19 UTC by kshxtij

Add macros for logging something only once or n times to reduce spam in logs

2022-11-21 19:08 UTC, kshxtij commented on lib/core/logger.hpp
> +  } while (0)
We don't want it to run n times, that exists to group multiple lines of code into a single macro

2022-11-21 19:13 UTC, SnickeyX commented on lib/core/logger.hpp
> +  } while (0)
`static int count` remaining `static` throughout breaks me but yes

2022-11-21 19:13 UTC, SnickeyX approved these changes

2022-11-22 11:50 UTC, mifrandir requested changes

2022-11-22 11:50 UTC, mifrandir commented on lib/core/logger.hpp
> +#define logOnce(logger, level, ...) logNTimes(logger, 1, level, __VA_ARGS__)
what's this?

2022-11-22 11:50 UTC, mifrandir commented on lib/core/logger.hpp
> +      count++;                                                                                     \
prefix

2022-11-22 11:50 UTC, mifrandir commented on lib/core/logger.hpp
> +    static int count = 0;                                                                          \
`std::size_t`

2022-12-29 20:48 UTC, kshxtij commented
@mifrandir could i get a review whenever you have time?

2022-12-30 11:36 UTC, mifrandir approved these changes
another cool thing would be "log every nth time"

2023-01-03 10:12 UTC, mifrandir requested changes

2023-01-03 10:12 UTC, mifrandir commented on lib/core/logger.hpp
> +    if (count % n == 0) { logger.log(level, __VA_ARGS__); }                                        \
check `count == n` and reset the counter to avoid overflows

2023-01-03 10:12 UTC, mifrandir commented on test/core/logger.cpp
> +    logEveryNth(logger, 5, core::LogLevel::kDebug, "test");
advance manual time to make sure the right logs are printed?

2023-01-23 19:06 UTC, maxguy2001 reviewed
Quick mac compliation fix and arbitrary style-guide changes but otherwise all good.

2023-01-23 19:06 UTC, maxguy2001 commented on test/core/logger.cpp
> +  for (int i = 0; i < 15; i++) {
size_t and pre-incrementing

2023-01-23 19:06 UTC, maxguy2001 commented on test/core/logger.cpp
> +  for (int i = 0; i < 5; i++) {
size_t and pre-incrementing

2023-01-24 12:31 UTC, mifrandir approved these changes
modulo max's changes

2023-01-26 11:03 UTC, kshxtij commented
This builds locally, i'll track down what's causing CI to fail and merge this later today.

2023-01-26 14:19 UTC, maxguy2001 commented
> This builds locally, i'll track down what's causing CI to fail and merge this later today.

It's the macos security thing. Merging master into this branch should fix it (directly fixing problem will give you merge conflict).

2023-01-27 13:14 UTC, merged