REPL: Temperature Sensor
Hyp-ed/hyped-2023 pull request #57
Opened 2022-11-21 21:57 UTC by kshxtij

Add support for single temperature sensor testing with debug binary

2022-11-24 18:30 UTC, Platiniom64 approved these changes

2022-11-24 18:31 UTC, HTTYDKing approved these changes

2022-11-30 22:59 UTC, SnickeyX requested changes

2022-11-30 22:59 UTC, SnickeyX commented on lib/debug/repl.cpp
> +    const auto value = temperature->read();
also want to test this with temp sns mid dec anyway so we can merge right aft we know it works

2022-12-26 13:21 UTC, SnickeyX commented on lib/debug/repl.cpp
> +    const auto value = temperature->read();
^ well that didn't happen, testing this the week we are back in sem2

2023-01-26 11:42 UTC, kshxtij commented
@SnickeyX Due to the bug you discovered, I'm assuming this is going to be a more overarching change that we first expected. Thoughts on me closing this for your team to open up a PR with the fixes + Accelerometer + Temperature commands?

2023-01-27 13:09 UTC, closed without merging