feat(tel-server): Add dictionary plugin
Hyp-ed/hyped-2023 pull request #95
Opened 2023-02-16 18:03 UTC by arjunnaha

2023-02-16 18:18 UTC, davidbeechey requested changes
Looks good. Can we remove the EVAL warning suppression from the vite config?

2023-02-16 18:19 UTC, arjunnaha commented
@davidbeechey yep! Let me do that now.

Is the build all fine on your laptop now?

2023-02-16 18:26 UTC, davidbeechey commented
@arjunnaha yeah all good running on WSL - was just being a problem on Windows 🙃

2023-03-02 17:44 UTC, kshxtij approved these changes

2023-03-02 21:11 UTC, merged