Ss brake emergency
Hyp-ed/hyped-2023 pull request #99
Opened 2023-02-27 18:44 UTC by Knhwong

First commit

2023-02-28 17:41 UTC, maxguy2001 requested changes

2023-02-28 17:41 UTC, maxguy2001 commented on lib/brakes/brakes.cpp
> +brakes::BrakeClass(const std::uint8_t pin_, const hyped::io::HardwareGpio gpio)
Naming - `BrakeClass`?

2023-02-28 17:41 UTC, maxguy2001 commented on lib/brakes/brakes.cpp
> +  pin    = pin_;
Think you're getting naming conventions mixed up here. Class data members have an underscore at the end, function arguments do not (i.e. should be `pin_=pin`).

2023-02-28 17:41 UTC, maxguy2001 commented on lib/brakes/brakes.hpp
> +#include <optional>
not used

2023-02-28 17:41 UTC, maxguy2001 commented on lib/brakes/brakes.hpp
> +  BrakeClass(const std::uint8_t pin_, const hyped::io::HardwareGpio gpio);
documention.

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.cpp
> +  if (*gpio_readAddr & pin_map) {
and `pin_map_`

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.cpp
> +  const std::uint32_t bank = pin / 32;
and elsewhere. Don't think you need uint32_t here?

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.cpp
> +  std::shared_ptr<IGpioReader> reader = initialized_readers_[pin];
For sake of consistency in the codebase.

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.hpp
> +static constexpr std::uint32_t pin_size  = 0x1000;
`kPinSize`?

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.hpp
> +static constexpr std::uint32_t pin_size  = 0x1000;
Also this feels like quite a high scope to be declaring these? Is there absolutely nothing else in `hyped::io` that could be called `pin_size`?

2023-02-28 17:41 UTC, maxguy2001 commented on lib/io/hardware_gpio.hpp
> +  const std::uint8_t pin_map;
naming

2023-03-06 18:46 UTC, closed without merging

2023-03-06 18:47 UTC, Knhwong commented
Changed to BrakesClean to base of main.